# Generated by Django 4.2.11 on 2024-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
