# Generated by Django 4.2.11 on 2024-04-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0002_driver_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
