# Generated by Django 4.2.11 on 2024-04-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0003_alter_driver_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
