# Generated by Django 4.2.11 on 2024-04-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='lauda.vehicle'),
        ),
    ]
