# Generated by Django 4.2.11 on 2024-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0006_alter_driver_vehicle_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
    ]
