# Generated by Django 4.2.11 on 2024-05-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0007_alter_driver_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
