# Generated by Django 4.2.11 on 2024-05-02 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lauda', '0010_remove_driver_vehicle_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='lauda.driver'),
        ),
    ]
